-- ============================================================================
-- project-assets storage bucket: per-project glossaries and style guides
-- uploaded by staff and surfaced to vendors via vendor-get-job-detail.
--
-- Path scheme: {project_id}/glossary/{filename}
--              {project_id}/style-guide/{filename}
--
-- Vendors do NOT access this bucket directly; they receive signed URLs
-- generated by the service-role edge function. Authenticated staff have
-- full CRUD via the admin portal.
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'project-assets',
  'project-assets',
  false,
  52428800, -- 50 MB
  ARRAY[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.oasis.opendocument.text',
    'application/vnd.oasis.opendocument.spreadsheet',
    'text/plain',
    'text/csv',
    'text/markdown'
  ]::text[]
)
ON CONFLICT (id) DO NOTHING;

-- Storage policies — staff (authenticated) full CRUD; service_role for edge functions.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='Authenticated can read project-assets') THEN
    CREATE POLICY "Authenticated can read project-assets" ON storage.objects
      FOR SELECT TO authenticated USING (bucket_id = 'project-assets');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='Authenticated can insert project-assets') THEN
    CREATE POLICY "Authenticated can insert project-assets" ON storage.objects
      FOR INSERT TO authenticated WITH CHECK (bucket_id = 'project-assets');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='Authenticated can update project-assets') THEN
    CREATE POLICY "Authenticated can update project-assets" ON storage.objects
      FOR UPDATE TO authenticated USING (bucket_id = 'project-assets') WITH CHECK (bucket_id = 'project-assets');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='Authenticated can delete project-assets') THEN
    CREATE POLICY "Authenticated can delete project-assets" ON storage.objects
      FOR DELETE TO authenticated USING (bucket_id = 'project-assets');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='Service role full access on project-assets') THEN
    CREATE POLICY "Service role full access on project-assets" ON storage.objects
      FOR ALL TO service_role USING (bucket_id = 'project-assets') WITH CHECK (bucket_id = 'project-assets');
  END IF;
END $$;
