// =============================================================================
// stripe-webhook/index.ts
//
// Handles Stripe webhook events for the customer quote payment flow.
// Primary event: checkout.session.completed — creates an order from the
// quote, records the payment, and expires the checkout session so it cannot
// be reused (prevents duplicate charges).
//
// Deployed with --no-verify-jwt (Stripe sends raw POST, no Supabase auth).
// =============================================================================

import { serve } from "https://deno.land/std@0.208.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import Stripe from "https://esm.sh/stripe@13.3.0?target=deno";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, stripe-signature",
};

function jsonResp(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const stripeKey = Deno.env.get("STRIPE_SECRET_KEY");
  const webhookSecret = Deno.env.get("STRIPE_WEBHOOK_SECRET");
  if (!stripeKey || !webhookSecret) {
    console.error("Missing STRIPE_SECRET_KEY or STRIPE_WEBHOOK_SECRET");
    return jsonResp({ error: "Not configured" }, 500);
  }

  const stripe = new Stripe(stripeKey, { apiVersion: "2023-10-16" });

  // ── Verify Stripe signature ───────────────────────────────────────────────
  const sig = req.headers.get("stripe-signature");
  if (!sig) {
    return jsonResp({ error: "Missing stripe-signature header" }, 400);
  }

  const body = await req.text();
  let event: Stripe.Event;
  try {
    event = await stripe.webhooks.constructEventAsync(body, sig, webhookSecret);
  } catch (err: any) {
    console.error("Webhook signature verification failed:", err.message);
    return jsonResp({ error: "Invalid signature" }, 400);
  }

  // Only handle checkout.session.completed for quote payments
  if (event.type !== "checkout.session.completed") {
    return jsonResp({ received: true });
  }

  const session = event.data.object as Stripe.Checkout.Session;
  const quoteId = session.metadata?.quote_id;
  if (!quoteId) {
    console.log("No quote_id in session metadata — not a quote payment, skipping");
    return jsonResp({ received: true });
  }

  const sb = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { auth: { autoRefreshToken: false, persistSession: false } },
  );

  try {
    await processQuotePayment(sb, stripe, session, quoteId);
    return jsonResp({ received: true });
  } catch (err: any) {
    console.error("stripe-webhook processing error:", err.message);
    return jsonResp({ error: err.message }, 500);
  }
});

// ── Core: convert quote → order + record payment ────────────────────────────
async function processQuotePayment(
  sb: ReturnType<typeof createClient>,
  stripe: Stripe,
  session: Stripe.Checkout.Session,
  quoteId: string,
) {
  // Fetch quote
  const { data: quote, error: qErr } = await sb
    .from("quotes")
    .select(
      `id, quote_number, status, customer_id, converted_to_order_id,
       subtotal, certification_total, rush_fee, delivery_fee,
       tax_rate, tax_amount, total,
       estimated_delivery_date, certification_type_id,
       turnaround_type, currency`,
    )
    .eq("id", quoteId)
    .single();

  if (qErr || !quote) {
    throw new Error(`Quote not found: ${quoteId}`);
  }

  // ── Idempotency: already converted ────────────────────────────────────────
  if (quote.converted_to_order_id) {
    console.log(
      `Quote ${quote.quote_number} already converted → ${quote.converted_to_order_id}`,
    );
    return;
  }

  // ── Create order (order_number auto-generated by DB trigger) ──────────────
  const totalAmount = Number(quote.total || 0);
  const currency = (quote.currency || session.currency || "CAD").toUpperCase();

  const { data: order, error: orderErr } = await sb
    .from("orders")
    .insert({
      quote_id: quote.id,
      customer_id: quote.customer_id,
      status: "paid",
      work_status: "pending",
      subtotal: quote.subtotal || 0,
      certification_total: quote.certification_total || 0,
      rush_fee: quote.rush_fee || 0,
      delivery_fee: quote.delivery_fee || 0,
      tax_rate: quote.tax_rate || 0,
      tax_amount: quote.tax_amount || 0,
      total_amount: totalAmount,
      amount_paid: totalAmount,
      balance_due: 0,
      currency,
      estimated_delivery_date: quote.estimated_delivery_date || null,
      certification_type_id: quote.certification_type_id || null,
      is_rush: quote.turnaround_type === "rush",
      paid_at: new Date().toISOString(),
    })
    .select("id, order_number")
    .single();

  if (orderErr || !order) {
    throw new Error(`Failed to create order: ${orderErr?.message}`);
  }

  console.log(
    `Order created: ${order.order_number} from quote ${quote.quote_number}`,
  );

  // ── Record payment ────────────────────────────────────────────────────────
  const amountPaid = (session.amount_total || 0) / 100;
  const paymentIntent =
    typeof session.payment_intent === "string"
      ? session.payment_intent
      : (session.payment_intent as any)?.id;

  const { error: payErr } = await sb.from("payments").insert({
    order_id: order.id,
    amount: amountPaid,
    currency,
    payment_type: "stripe_checkout",
    payment_method: "card",
    status: "completed",
    stripe_checkout_session_id: session.id,
    stripe_payment_intent_id: paymentIntent || null,
  });

  if (payErr) {
    console.error("Failed to create payment record:", payErr.message);
  }

  // ── Update quote: mark paid, link to order ────────────────────────────────
  const { error: quoteUpdateErr } = await sb
    .from("quotes")
    .update({
      status: "paid",
      converted_to_order_id: order.id,
      stripe_checkout_session_id: session.id,
      paid_at: new Date().toISOString(),
    })
    .eq("id", quoteId);

  if (quoteUpdateErr) {
    console.error("Failed to update quote:", quoteUpdateErr.message);
  }

  // ── Expire the checkout session to prevent reuse ──────────────────────────
  try {
    await stripe.checkout.sessions.expire(session.id);
    console.log("Expired checkout session:", session.id);
  } catch (expireErr: any) {
    // Already completed sessions can't be expired — that's fine
    console.log("Session expire skipped (likely already completed):", expireErr.message);
  }

  // ── Enrich payment with card details (non-blocking) ───────────────────────
  try {
    if (paymentIntent) {
      const pi = await stripe.paymentIntents.retrieve(paymentIntent);
      const chargeId =
        typeof pi.latest_charge === "string"
          ? pi.latest_charge
          : (pi.latest_charge as any)?.id;

      if (chargeId) {
        const charge = await stripe.charges.retrieve(chargeId);
        const card = charge.payment_method_details?.card;
        if (card) {
          await sb
            .from("payments")
            .update({
              stripe_charge_id: chargeId,
              card_brand: card.brand,
              card_last4: card.last4,
              card_exp_month: card.exp_month,
              card_exp_year: card.exp_year,
              card_country: card.country,
              receipt_url: charge.receipt_url,
              stripe_enriched_at: new Date().toISOString(),
            })
            .eq("stripe_checkout_session_id", session.id);
        }
      }
    }
  } catch (enrichErr: any) {
    console.warn("Card enrichment failed (non-blocking):", enrichErr.message);
  }

  // ── Activity log ──────────────────────────────────────────────────────────
  try {
    await sb.from("staff_activity_log").insert({
      action_type: "quote_paid_stripe",
      entity_type: "order",
      entity_id: order.id,
      details: {
        quote_id: quote.id,
        quote_number: quote.quote_number,
        order_number: order.order_number,
        amount_paid: amountPaid,
        stripe_session_id: session.id,
        stripe_payment_intent: paymentIntent,
      },
    });
  } catch {
    // non-blocking
  }

  console.log(
    `Quote ${quote.quote_number} → Order ${order.order_number}, $${amountPaid} ${currency}`,
  );
}
